# First Aid mod definition file
modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="https://github.com/ichttft/firstaid"
displayURL="https://minecraft.curseforge.com/projects/first-aid"
logoFile="firstaid_logo.png"
authors="ichttt"
[[mods]]
    modId="firstaid"
    version="${file.jarVersion}"
    displayName="First Aid"
    description="First Aid is a game changing mod focused around a new health system"
[[dependencies.firstaid]]
    modId="forge"
    mandatory=true
    versionRange="[28.0.91,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.firstaid]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3,1.15)"
    ordering="NONE"
    side="BOTH"